export interface QuestionSection {
    readonly id: string;
    readonly title: string;
    readonly description: string;
    readonly category: string;
    readonly source: string;
    readonly output: string;
    readonly href: string;
}

export const questionSections = [
    {
        id: 'angular',
        title: 'Angular',
        description: 'Вопросы и ответы по Angular.',
        category: 'Frontend',
        source: 'questions/angular/README.md',
        output: 'questions/angular/index.html',
        href: './questions/angular/',
    },
    {
        id: 'react',
        title: 'React',
        description: 'Вопросы и ответы по React.',
        category: 'Frontend',
        source: 'questions/react/README.md',
        output: 'questions/react/index.html',
        href: './questions/react/',
    },
    {
        id: 'css',
        title: 'CSS',
        description: 'Вопросы и ответы по CSS.',
        category: 'Frontend',
        source: 'questions/css/README.md',
        output: 'questions/css/index.html',
        href: './questions/css/',
    },
    {
        id: 'typescript',
        title: 'TypeScript',
        description: 'Вопросы и ответы по TypeScript.',
        category: 'Frontend',
        source: 'questions/typescript/README.md',
        output: 'questions/typescript/index.html',
        href: './questions/typescript/',
    },
    {
        id: 'javascript',
        title: 'JavaScript',
        description: 'Вопросы и ответы по JavaScript.',
        category: 'Frontend',
        source: 'questions/javascript/README.md',
        output: 'questions/javascript/index.html',
        href: './questions/javascript/',
    },
    {
        id: 'computer-science',
        title: 'Computer Science',
        description: 'Базовые вопросы по Computer Science.',
        category: 'Engineering Fundamentals',
        source: 'questions/computer-science/README.md',
        output: 'questions/computer-science/index.html',
        href: './questions/computer-science/',
    },
    {
        id: 'web-platform',
        title: 'Web Platform',
        description: 'Вопросы и ответы по Web Platform.',
        category: 'Frontend',
        source: 'questions/web-platform/README.md',
        output: 'questions/web-platform/index.html',
        href: './questions/web-platform/',
    },
    {
        id: 'nodejs',
        title: 'Node.js',
        description: 'Вопросы и ответы по Node.js.',
        category: 'Backend',
        source: 'questions/nodejs/README.md',
        output: 'questions/nodejs/index.html',
        href: './questions/nodejs/',
    },
    {
        id: 'state-management',
        title: 'State Management',
        description: 'Вопросы и ответы по управлению состоянием.',
        category: 'Frontend',
        source: 'questions/state-management/README.md',
        output: 'questions/state-management/index.html',
        href: './questions/state-management/',
    },
    {
        id: 'soft-skills',
        title: 'Soft Skills',
        description: 'Вопросы и ответы по soft skills.',
        category: 'Career',
        source: 'questions/soft-skills/README.md',
        output: 'questions/soft-skills/index.html',
        href: './questions/soft-skills/',
    },
    {
        id: 'job-search',
        title: 'Job Search',
        description: 'Вопросы и ответы про поиск работы и собеседования.',
        category: 'Career',
        source: 'questions/job-search/README.md',
        output: 'questions/job-search/index.html',
        href: './questions/job-search/',
    },
    {
        id: 'methodologies',
        title: 'Methodologies',
        description: 'Вопросы и ответы по инженерным методологиям.',
        category: 'Engineering',
        source: 'questions/methodologies/README.md',
        output: 'questions/methodologies/index.html',
        href: './questions/methodologies/',
    },
    {
        id: 'infrastructure',
        title: 'Infrastructure',
        description: 'Вопросы и ответы по инфраструктуре, CI/CD и tooling.',
        category: 'Engineering',
        source: 'questions/infrastructure/README.md',
        output: 'questions/infrastructure/index.html',
        href: './questions/infrastructure/',
    },
    {
        id: 'programming',
        title: 'Programming',
        description: 'Общие вопросы по программированию.',
        category: 'Engineering Fundamentals',
        source: 'questions/programming/README.md',
        output: 'questions/programming/index.html',
        href: './questions/programming/',
    },
    {
        id: 'work-environment',
        title: 'Work Environment',
        description: 'Вопросы и ответы про рабочую среду.',
        category: 'Career',
        source: 'questions/work-environment/README.md',
        output: 'questions/work-environment/index.html',
        href: './questions/work-environment/',
    },
] satisfies readonly QuestionSection[];
